// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'navHeader': string;
  'navItem': string;
  'navList': string;
  'navWrap': string;
}
export const cssExports: CssExports;
export default cssExports;
