// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'header': string;
  'productPrice': string;
  'productStatus': string;
  'range': string;
  'rangeList': string;
  'rangeWrap': string;
  'search': string;
  'searchBtn': string;
  'searchInput': string;
  'treasure': string;
  'treasureList': string;
  'treasure_img': string;
  'treasure_price': string;
  'treasure_sale': string;
  'treasure_title': string;
}
export const cssExports: CssExports;
export default cssExports;
